/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'ownership-registrations': OwnershipRegistration;
    'licensing-requests': LicensingRequest;
    'construction-requests': ConstructionRequest;
    'funding-partner-requests': FundingPartnerRequest;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    'ownership-registrations': OwnershipRegistrationsSelect<false> | OwnershipRegistrationsSelect<true>;
    'licensing-requests': LicensingRequestsSelect<false> | LicensingRequestsSelect<true>;
    'construction-requests': ConstructionRequestsSelect<false> | ConstructionRequestsSelect<true>;
    'funding-partner-requests': FundingPartnerRequestsSelect<false> | FundingPartnerRequestsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ownership-registrations".
 */
export interface OwnershipRegistration {
  id: string;
  reviewStatus: 'new' | 'in-review' | 'contacted' | 'closed';
  fullName: string;
  governorate: string;
  phone: string;
  email?: string | null;
  cooperative: 'الطلائع' | 'مصر الجديدة' | 'أحمد عرابي' | 'الأمل' | 'القادسية' | 'مصر التعاونية' | 'اتحاد الوفاق';
  applicationStatus: string;
  areaUnit: 'feddan' | 'meter';
  plotNumber: string;
  basinNumber?: string | null;
  lineNumber?: string | null;
  feddanCount?: number | null;
  hasResidentialPlot?: boolean | null;
  residentialPlotArea?: number | null;
  isBuilt?: boolean | null;
  meterArea?: number | null;
  sellerName?: string | null;
  ownershipChain?: string | null;
  ownershipChainDocuments?: (string | Media)[] | null;
  sizeSelection: string;
  buildingDescription?: string | null;
  buildingPhotos?: (string | Media)[] | null;
  ownershipDocuments?: (string | Media)[] | null;
  areaMaps?: (string | Media)[] | null;
  notes?: string | null;
  ownerIdCard?: (string | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licensing-requests".
 */
export interface LicensingRequest {
  id: string;
  reviewStatus: 'new' | 'in-review' | 'contacted' | 'closed';
  serviceType: 'تصميم هندسي' | 'استصدار رخصة';
  plotAreaSqm: number;
  plotNumber: string;
  districtNumber: string;
  neighborhoodNumber: string;
  allocationNotices?: (string | Media)[] | null;
  fullName: string;
  nationalId: string;
  governorate: string;
  phone: string;
  email?: string | null;
  ownerType: 'مالك أساسي' | 'بتوكيل';
  nationalIdPhotos?: (string | Media)[] | null;
  powerOfAttorneyDocuments?: (string | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "construction-requests".
 */
export interface ConstructionRequest {
  id: string;
  reviewStatus: 'new' | 'in-review' | 'contacted' | 'closed';
  workDescription: string;
  contactName: string;
  contactPhone: string;
  contactEmail?: string | null;
  allocationNotices?: (string | Media)[] | null;
  receiptMinutes?: (string | Media)[] | null;
  licenseDocuments?: (string | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "funding-partner-requests".
 */
export interface FundingPartnerRequest {
  id: string;
  reviewStatus: 'new' | 'in-review' | 'contacted' | 'closed';
  ownershipStatus: 'اسم على صفحة الجهاز' | 'إخطار تخصيص';
  partnershipType: 'شراكة برسوم التقنين' | 'شراكة برسوم التقنين والمباني' | 'شراكة بالمباني فقط';
  landAreaSqm?: number | null;
  tanqinSeriousnessPaid?: boolean | null;
  contactName: string;
  contactPhone: string;
  contactEmail?: string | null;
  allocationNotices?: (string | Media)[] | null;
  receiptMinutes?: (string | Media)[] | null;
  licenseDocuments?: (string | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'ownership-registrations';
        value: string | OwnershipRegistration;
      } | null)
    | ({
        relationTo: 'licensing-requests';
        value: string | LicensingRequest;
      } | null)
    | ({
        relationTo: 'construction-requests';
        value: string | ConstructionRequest;
      } | null)
    | ({
        relationTo: 'funding-partner-requests';
        value: string | FundingPartnerRequest;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ownership-registrations_select".
 */
export interface OwnershipRegistrationsSelect<T extends boolean = true> {
  reviewStatus?: T;
  fullName?: T;
  governorate?: T;
  phone?: T;
  email?: T;
  cooperative?: T;
  applicationStatus?: T;
  areaUnit?: T;
  plotNumber?: T;
  basinNumber?: T;
  lineNumber?: T;
  feddanCount?: T;
  hasResidentialPlot?: T;
  residentialPlotArea?: T;
  isBuilt?: T;
  meterArea?: T;
  sellerName?: T;
  ownershipChain?: T;
  ownershipChainDocuments?: T;
  sizeSelection?: T;
  buildingDescription?: T;
  buildingPhotos?: T;
  ownershipDocuments?: T;
  areaMaps?: T;
  notes?: T;
  ownerIdCard?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licensing-requests_select".
 */
export interface LicensingRequestsSelect<T extends boolean = true> {
  reviewStatus?: T;
  serviceType?: T;
  plotAreaSqm?: T;
  plotNumber?: T;
  districtNumber?: T;
  neighborhoodNumber?: T;
  allocationNotices?: T;
  fullName?: T;
  nationalId?: T;
  governorate?: T;
  phone?: T;
  email?: T;
  ownerType?: T;
  nationalIdPhotos?: T;
  powerOfAttorneyDocuments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "construction-requests_select".
 */
export interface ConstructionRequestsSelect<T extends boolean = true> {
  reviewStatus?: T;
  workDescription?: T;
  contactName?: T;
  contactPhone?: T;
  contactEmail?: T;
  allocationNotices?: T;
  receiptMinutes?: T;
  licenseDocuments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "funding-partner-requests_select".
 */
export interface FundingPartnerRequestsSelect<T extends boolean = true> {
  reviewStatus?: T;
  ownershipStatus?: T;
  partnershipType?: T;
  landAreaSqm?: T;
  tanqinSeriousnessPaid?: T;
  contactName?: T;
  contactPhone?: T;
  contactEmail?: T;
  allocationNotices?: T;
  receiptMinutes?: T;
  licenseDocuments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}